name: flutter_status_overlay
description: A versatile and easy-to-use package for displaying customizable status messages in Flutter apps. Enhance user feedback with elegant overlays for both error and success notifications.
version: 0.0.4
homepage: https://github.com/larivasi/flutter_status_overlay
tags: [flutter, overlay, status, error, success, notification, message, feedback]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
